apiVersion: v1
baseDomain: catchall.azure.devcluster.openshift.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: {{ .WorkerReplicas }}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: {{ .MasterReplicas }}
metadata:
  creationTimestamp: null
  name: {{ .ClusterName }}
networking:
  clusterNetwork:
  - cidr: {{ .ClusterCidr }}
    hostPrefix: {{ .ClusterCidrHostPrefix }}
  machineNetwork: {{range .MachineCidr}}
  - cidr: {{.}}{{end}}
  networkType: {{ .NetworkType }}
  serviceNetwork:
  - {{ .ServiceCidr }}
platform:
  azure:
    baseDomainResourceGroupName: os4-common
    region: {{ .ProviderRegion }}
pullSecret: '{{ .PullSecret }}'
sshKey: |
  {{ .SSHKey }}
