apiVersion: v1
baseDomain: hexfusion.local
compute:
  - hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 1
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: {{ .ClusterName }}
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
pullSecret: '{{ .PullSecret }}'
sshKey: |
  {{ .SSHKey }}